### ISSUE TITLE
Problem with Package when installing from Flathub

### ISSUE THREAD

**Issue by egrath** [flathub/com.xnview.XnRetro#2]
When installing this package from Flathub, the dependency 
<code>org.freedesktop.Platform/i386/18.08</code> gets not installed automatically. You have to manually issue <code>flatpak install -y flathub org.freedesktop.Platform/i386/18.08</code> to fix it.

**Comment by scx** [comment]
@egrath 

> When installing this package from Flathub, the dependency
> `org.freedesktop.Platform/i386/18.08` gets not installed automatically. You have to manually issue `flatpak install -y flathub org.freedesktop.Platform/i386/18.08` to fix it.

Thanks for reporting!
What is your flatpak version? Does it fail, or just install anyway? In other words, have you been able to install the XnRetro package without runtime (Freedesktop)? Anyway, it should not happen.

It may be related to this issue:
https://github.com/flatpak/flatpak/issues/2784

@alexlarsson @nedrichards 
Any idea why this behaves like that?

**Comment by egrath** [comment]
My flatpak version:
<code>com.xnview.XnRetro/i386/stable	flathub	ae48c0e9f2c7	-	127,6 MB	system,current</code>
it installs without any problem, but when i run, it complains about the missing dependency:
<code>egon@endless:~$ flatpak run com.xnview.XnRetro
error: runtime/org.freedesktop.Platform/i386/18.08 not installed</code>

**Comment by scx** [comment]
@egrath 

> My flatpak version:
> `com.xnview.XnRetro/i386/stable	flathub	ae48c0e9f2c7	-	127,6 MB	system,current`

I was asking about the flatpak version in your system: `flatpak --version`
```
$ flatpak --version
Flatpak 1.0.2
```

> it installs without any problem, but when i run, it complains about the missing dependency:
> `egon@endless:~$ flatpak run com.xnview.XnRetro`
> `error: runtime/org.freedesktop.Platform/i386/18.08 not installed`

Strange. It definitely shouldn't happen.

**Comment by scx** [comment]
From IRC channel:
> 11:39 < alexlarsson> scx: that seems very strange? if an app depends on a particular runtime is should always install it or fail
> 11:39 < alexlarsson> does it fail, or just install anyway?
> 11:43 < nedrichards> that, er, should not happen
> 11:44 < bochecha> it installs the runtime here
> 11:44 < bochecha> maybe the reporter is using an old flatpak/gnome-software which had a bug?
> 11:54 < scx> alexlarsson: It is an i386 package, probably on x86_64 host.
> 11:54 < scx> Can it make any difference?
> 11:55 < scx> Maybe it is trying to install x86_64 version of Freedesktop runtime?
> 11:55 < bochecha> scx, I'm on a x86_64 host, and it worked installing the i386 runtime as a dep of the i386 app
> 11:56 < scx> So probably flatpak < 1.0, maybe 0.10?
> 11:56 < alexlarsson> I dunno, dependencies like that should have worked a *very* long way back
> 11:58 < bochecha> I found GNOME Software used to handle deps pretty badly in the beginning, whether at installation or update
> 11:59 < bochecha> it all seems to be fixed now, but I wonder whether the reporter wouldn't have an old version…
> 11:59 < bochecha> they didn't say how they installed

**Comment by egrath** [comment]
My flatpak version is
<code>Flatpak 1.0.0</code>
(Endless OS 3.5.7)

**Comment by wjt** [comment]
If you installed this with "App Center" / GNOME Software, this is a known issue with the version we ship. It should be fixed in a few months when we've rebased to a version of GNOME Software that uses FlatpakTransaction.
