### ISSUE TITLE
XnRetro doesn't run.

### ISSUE THREAD

**Issue by dfsdiogo** [flathub/com.xnview.XnRetro#3]
Xnretro doesn't run on my 'endless os'.
[eos-diagnostic-190409_142439_UTC-0300.txt](https://github.com/flathub/com.xnview.XnRetro/files/3061182/eos-diagnostic-190409_142439_UTC-0300.txt)

**Comment by scx** [comment]
@dfsdiogo 

Thanks for reporting!

I believe that this is a known Endless OS issue.
https://github.com/flathub/com.xnview.XnRetro/issues/2#issuecomment-477597316

```
abr 09 11:35:27 endless com.xnview.XnRetro.desktop[2463]: erro: runtime/org.freedesktop.Platform/i386/18.08 não instalado
```

You should try to install **Freedesktop** runtime manually:
```
flatpak install "flathub" "org.freedesktop.Platform/i386/18.08"
```

Then try run **XnRetro** again:
```
flatpak run "com.xnview.XnRetro"
```

@wjt 

Would you like to add something?

**Comment by wjt** [comment]
I have nothing to add!

**Comment by scx** [comment]
Actually, there is already a topic on Endless OS forum:

https://community.endlessos.com/t/programa-xnretro-nao-inicia/9229/4

> This is a known issue. Open a terminal window and run:
> 
> ```flatpak install --system -y flathub org.freedesktop.Platform/i386/18.08```
> 
> This is expected to be resolved in a future release of Endless OS.

**Comment by dfsdiogo** [comment]
Works fine!
Thanks github team!

Em qua, 10 de abr de 2019 às 07:50, scx <notifications@github.com> escreveu:

**Comment by bbhtt** [comment]
Hello, is this still an issue?

**Comment by bbhtt** [comment]
Actually, looks like this is an issue with flatpak not following dependencies https://github.com/flatpak/flatpak/issues/4164

I'll add something in the readme here

**Comment by bbhtt** [comment]
> Actually, looks like this is an issue with flatpak not following dependencies [flatpak/flatpak#4164](https://github.com/flatpak/flatpak/issues/4164)
> 
> I'll add something in the readme here

Scratch that. It works without needing to do anything:

```
flatpak install flathub com.xnview.XnRetro

Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1
Required runtime for com.xnview.XnRetro/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/20.08) found in remote flathub
Do you want to install it? [Y/n]: y

com.xnview.XnRetro permissions:
    ipc           network      x11      dri     multiarch     file access [1]
    tags [2]

    [1] home
    [2] proprietary


        ID                                              Branch            Op           Remote            Download
 1.     com.xnview.XnRetro.Locale                       stable            i            flathub             < 6.8 MB (partial)
 2.     org.freedesktop.Platform.Compat.i386            20.08             i            flathub           < 153.4 MB
 3.     org.freedesktop.Platform.GL.default             20.08             i            flathub           < 106.4 MB
 4.     org.freedesktop.Platform.Locale                 20.08             i            flathub           < 322.5 MB (partial)
 5.     org.freedesktop.Platform                        20.08             i            flathub           < 270.4 MB
 6.     com.xnview.XnRetro                              stable            i            flathub            < 51.1 MB
```

@nanonyme helped me find this. The extension isn't installed for test builds that the bot posts which I was trying.

No readme is needed. This can now be closed I think.
