### ISSUE TITLE
runtime org.freedesktop.Platform branch 20.08 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/com.xnview.XnRetro#6]
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

**Comment by bbhtt** [comment]
Hello, if you can test this PR https://github.com/flathub/com.xnview.XnRetro/pull/8 and let me know if everything works, I'd be grateful. Thanks!
