### ISSUE TITLE
XnRetro 1.30

### ISSUE THREAD

**Issue by MuellerSeb** [flathub/com.xnview.XnRetro#7]
According to the website, the current version is 1.30: https://www.xnview.com/de/xnretro/

Could this be updated here?

Thanks!

**Comment by bbhtt** [comment]
I'm working on this right now but I think I'll need to drop i386 support. The application doesn't ship with libcrypto and libssl libs so I need to compile openssl1, but having various errors with it. Also QT4 refuses to compile which is only needed for i386.

**Comment by bbhtt** [comment]
> According to the website, the current version is 1.30: 
> 
> Could this be updated here?
> 
> Thanks!

Actually the webpage is wrong. The last version was 1.26. If you look at the tarball it links to, the release is from 2013

![c21bf80b11](https://github.com/flathub/com.xnview.XnRetro/assets/62639087/8c7c650d-840d-477a-826a-7f96b3abb4f4)


I'll still try to update the runtime if I can but that's https://github.com/flathub/com.xnview.XnRetro/issues/6

Thanks!

**Comment by bbhtt** [comment]
By the way, if you can test this PR https://github.com/flathub/com.xnview.XnRetro/pull/8 and let me know if everything works, I'd be grateful. Thanks!
